def init():
    global DEV_MODE, DATA_FILE_PATH, UNIT, UPDATE_CMC_REFERENCE_DATA, UPDATE_DEFILLAMA_REFERENCE_DATA
    DEV_MODE = 'OFF'
    DATA_FILE_PATH = r'C:\Users\patri\Downloads\crypto-values-master\data-files'
    UNIT = 1000000000  # billion
    UPDATE_CMC_REFERENCE_DATA = 'OFF'
    UPDATE_DEFILLAMA_REFERENCE_DATA = 'ON'
